### PR TITLE
SystemD service

### PR DESCRIPTION
**Pull request by es20490446e**
As https://github.com/agalakhov/xiccd/issues/20.

For this to work someone needs to configure the building process to run "install.sh" or similar.

### CODE REVIEW

**Comment by es20490446e** [comment]
https://youtu.be/Ags9GWnkI10

**Comment by es20490446e** [comment]
If there are no updates on this I will provide the service in a separate repository meanwhile.

**Comment by agalakhov** [comment]
Your code seems to depend on `sudo` settings which is definitely NOT portable. It works for you, but it won't work for others (including me). I cannot accept this, sorry. Please make a more portable version.

**Comment by es20490446e** [comment]
Okay.

**Comment by es20490446e** [comment]
Done.

**Comment by es20490446e** [comment]
Notes for me:
- https://unix.stackexchange.com/questions/523398/how-to-reload-users-daemons-as-superuser
- https://unix.stackexchange.com/questions/523865/why-does-reloading-user-daemons-fail
- https://forum.manjaro.org/t/why-does-reloading-user-daemons-fail/90620

**Comment by es20490446e** [comment]
I decided to modify the design to make it easier to package.

**Pull request closed without merging**
